name: "Build"

on:
  push:
    branches: 
      - develop
  pull_request:
    branches: 
      - develop

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Build
        run: |
          npm install
          npm run build
        working-directory: ./card  